server:
  port: 8001


spring:
  application:
    name: cloud-u  ser-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/data_integration?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 110533

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.db.springcloud.entities   # 所有Entity别名类所在包

